/* *******************
 * AUTO-GENERATED FILE
 * *******************
 * @NOTE This file is automatically generated from the contents of `@fantasy-console/core`
 * To regenerate this file, run `npm run build:core.g`
 *
 * DO NOT EDIT THIS FILE MANUALLY, AS ANY CHANGES TO IT WILL BE OVERWRITTEN.
 */

import * as Core from '@fantasy-console/core';
import * as WorldGameObject from '@fantasy-console/core/src/world/GameObject';
import * as WorldGameObjectComponent from '@fantasy-console/core/src/world/GameObjectComponent';
import * as WorldTransform from '@fantasy-console/core/src/world/Transform';
import * as World from '@fantasy-console/core/src/world';
import * as WorldComponentsCameraComponent from '@fantasy-console/core/src/world/components/CameraComponent';
import * as WorldComponentsDirectionalLightComponent from '@fantasy-console/core/src/world/components/DirectionalLightComponent';
import * as WorldComponentsMeshComponent from '@fantasy-console/core/src/world/components/MeshComponent';
import * as WorldComponentsPointLightComponent from '@fantasy-console/core/src/world/components/PointLightComponent';
import * as WorldComponentsScriptComponent from '@fantasy-console/core/src/world/components/ScriptComponent';
import * as WorldComponents from '@fantasy-console/core/src/world/components';
import * as UtilVector2 from '@fantasy-console/core/src/util/Vector2';
import * as UtilVector3 from '@fantasy-console/core/src/util/Vector3';
import * as Util from '@fantasy-console/core/src/util';
import * as ModulesIModule from '@fantasy-console/core/src/modules/IModule';
import * as ModulesInput from '@fantasy-console/core/src/modules/Input';
import * as Modules from '@fantasy-console/core/src/modules';
import * as ModulesWorldWorldModule from '@fantasy-console/core/src/modules/World/WorldModule';
import * as ModulesWorldWorldQuery from '@fantasy-console/core/src/modules/World/WorldQuery';
import * as ModulesWorld from '@fantasy-console/core/src/modules/World';

export interface CoreModuleDefinition {
  name: string;
  module: any;
}

// @NOTE These are all the imports that will be injected into scripts
// defined at runtime
export const CoreModules: CoreModuleDefinition[] = [
  {
    name: '@fantasy-console/core',
    module: Core,
  },
  {
    name: '@fantasy-console/core/world/GameObject',
    module: WorldGameObject,
  },
  {
    name: '@fantasy-console/core/world/GameObjectComponent',
    module: WorldGameObjectComponent,
  },
  {
    name: '@fantasy-console/core/world/Transform',
    module: WorldTransform,
  },
  {
    name: '@fantasy-console/core/world',
    module: World,
  },
  {
    name: '@fantasy-console/core/world/components/CameraComponent',
    module: WorldComponentsCameraComponent,
  },
  {
    name: '@fantasy-console/core/world/components/DirectionalLightComponent',
    module: WorldComponentsDirectionalLightComponent,
  },
  {
    name: '@fantasy-console/core/world/components/MeshComponent',
    module: WorldComponentsMeshComponent,
  },
  {
    name: '@fantasy-console/core/world/components/PointLightComponent',
    module: WorldComponentsPointLightComponent,
  },
  {
    name: '@fantasy-console/core/world/components/ScriptComponent',
    module: WorldComponentsScriptComponent,
  },
  {
    name: '@fantasy-console/core/world/components',
    module: WorldComponents,
  },
  {
    name: '@fantasy-console/core/util/Vector2',
    module: UtilVector2,
  },
  {
    name: '@fantasy-console/core/util/Vector3',
    module: UtilVector3,
  },
  {
    name: '@fantasy-console/core/util',
    module: Util,
  },
  {
    name: '@fantasy-console/core/modules/IModule',
    module: ModulesIModule,
  },
  {
    name: '@fantasy-console/core/modules/Input',
    module: ModulesInput,
  },
  {
    name: '@fantasy-console/core/modules',
    module: Modules,
  },
  {
    name: '@fantasy-console/core/modules/World/WorldModule',
    module: ModulesWorldWorldModule,
  },
  {
    name: '@fantasy-console/core/modules/World/WorldQuery',
    module: ModulesWorldWorldQuery,
  },
  {
    name: '@fantasy-console/core/modules/World',
    module: ModulesWorld,
  }
];
